In this assignment you will be asked to extend the work by Gatti et al by checking whether form-meaning mappings learned on a different yet related language to that considered in the original study still capture the perceived valence of pseudowords. To do this you will be asked to engage with several different resources and adapt the pipeline following the instructions. Along the way, you will be asked to answer a few questions.

You need to submit the complete notebook in .ipynb format, with intermediate outputs visible. The notebook should be named as follows:

CL2025_groupN_assignment.ipynb

where N is the group number. Submissions in the wrong format or with names not adhering to the guidelines will not be evaluated.

Indicate group members' names, student numbers, and contributions below:
- 1.
- 2.
- 3.
- 4.
- 5.

I suggest that we use "##" for comments instead, to distinguish between our and the original comments, but idk if there is any standard for this -Frey

To do:
- get everyone setup and comfortable with git(hub)
- check if frey found the correct files

In [48]:
## This block has been modified to work for local usage 

# the code has been tested using the psycho-embeddings library to extract representations from LLMs. You can also use other libraries,
# as long as you make sure that you are producing the correct output.

## SETUP:
## Make sure you have Git and Pip installed then run the following commands in the command line (make sure you are an administrator of course)

#git clone https://github.com/MilaNLProc/psycho-embeddings.git
%pip install datasets
#pip install fasttext
%pip install nltk
%cd psycho-embeddings

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: datasets in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (3.5.0)
Requirement already satisfied: filelock in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (2.2.4)
Requirement already satisfied: pyarrow>=15.0.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (19.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: aiohttp in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (3.11.16)
Requirement already satisfied: huggingface-hub>=0.24.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (0.30.1)
Requirement already satisfied: packaging in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: nltk in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (3.9.1)
Requirement already satisfied: click in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /home/stefan/miniforge3/envs/CompLing/lib/python3.11/site-packages (from nltk) (4.67.1)
Note: you may need to restart the kernel to use updated packages.
/home/stefan/Documents/GitHub/CL_group8/psycho-embeddings

In [49]:
# the solution to the assignment has been obtained using these packages.
# you're free to use other packages though: consider this as an indication, not a prescription.
import nltk
import numpy as np
import pandas as pd
#import fasttext as ft
import pickle as pkl
#import fasttext.util
from tqdm import tqdm
from collections import defaultdict
from transformers import AutoTokenizer
#from psycho_embeddings import ContextualizedEmbedder

## psycho_embeddings throws a problems about tensorflow versions, but these are the same as the lecture 5 notebook
## so I assume they can be ignored

In [50]:
%cd ..

/home/stefan/Documents/GitHub/CL_group8

**Task 1** (*10 points available, see breakdown per task below*)

You should replicate the main design in the paper *Valence without meaning* by Gatti and colleagues (2024), using estimates collected for Dutch word valence to train linear regression models and apply them to predict the valence of English pseudowords from Gatti and colleagues.

In detail, to train your regression models, you should use the dataset by Speed and Brysbaert (2024) containing crowd-sourced valence ratings (use the metadata to identify the relevant columns) collected for approximately 24,000 Dutch words. See the paper *Ratings of valence, arousal, happiness, anger, fear, sadness, disgust, and surprise for 24,000 Dutch words* by Speed and Brysbaert (2024).

You should train a letter unigram model and a bigram model. Each model should be trained on Dutch words only.

Pay attention to one issue though: pseudowords created for English may be valid words in Dutch: therefore, you should first filter the list of pseudowords against a large store of Dutch words. To do so, use the words in the Dutch prevalence lexicon available in this OSF repository: https://osf.io/9zymw/. Essentially, you need to exclude any pseudoword that happens to be a word for which a prevalence estimate is available, whatever the prevalence is.

Each code block indicates how many points are available and how they are attributed.

In [51]:
# read in the pseudowords from Gatti and colleagues, as well as the valence ratings for 24,000 Dutch words from Speed and Brysbaert (2024)
# show the first 5 lines of each dataset.
# 1 point for identifying the correct files and correctly loading their content

In [52]:
# import os
# os.chdir(r"C:\Users\hajko\Desktop\Methods\CL_group8")

In [53]:
## getting the pseudowords from Gatti -Frey

## I am using a pandas dataframe (df)
## pseudowords_Gatti is called comb_2 in the Rdata file

df_Gatti = pd.read_csv("Gatti_pseudowords_and_valence.csv")
df_Gatti.head(5)

  pseudoword     Value
0     abhert  0.452501
1     abhict  0.434171
2     acleat  0.527803
3     acmure  0.604889
4      acoed  0.538990

In [54]:
## Getting the word valence from Speed -Frey

## I have uploaded the file as wordvalence_Speed.csv after I have saved "All_Valence" as a csv
df_Speed = pd.read_csv("wordvalence_Speed.csv")
df_Speed.head(5)

,Word,Arousal,Valence,ValenceCategory,ValenceVsNeutral,Happiness,Anger,Fear,Sadness,Disgust,...,Length,Nsyl,N_phonemes,PoS,OLD20,AoA,DLP_RT,DLP_Acc,DCP_RT,DCP_Acc
0,mama,2.812500,4.000000,positive,valenced,3.300000,1.000000,1.000000,1.100000,1.000000,...,4,2,4,N,1.55,2.044257,513.530256,1.000000,931.03,0.99
1,ja,2.823529,3.894737,positive,valenced,3.818182,1.090909,1.181818,1.181818,1.000000,...,2,1,2,Function,1.00,2.250000,494.980294,1.000000,1014.77,1.00
2,papa,2.562500,3.722222,positive,valenced,4.142857,1.142857,1.000000,1.000000,1.000000,...,4,2,4,N,1.65,2.336327,570.497647,1.000000,936.88,0.99
3,nee,2.928571,2.350000,negative,neutral,1.000000,1.727273,1.363636,1.454545,1.363636,...,3,1,2,Function,1.00,2.555556,488.637879,0.902439,1088.01,1.00
4,kaka,3.357143,2.050000,negative,neutral,1.090909,1.454545,1.181818,1.000000,4.727273,...,4,2,4,N,1.80,2.611111,629.402647,0.850000,1605.49,0.53

In [55]:
# filter out pseudowords that happen to be valid Dutch words (mind case folding!)
# show the set of pseudowords filtered out.
# 1 point for applying the correct filtering

In [56]:
## Combining the file for the prevalence of Dutch words and Belgian words -Frey
df_prevalence_Netherlands = pd.read_csv("prevalence_netherlands.csv" , sep = "\t")
df_prevalence_Belgium = pd.read_csv("prevalence_belgium.csv", sep= "\t")

df_prevalence_combined = pd.concat([df_prevalence_Belgium, df_prevalence_Netherlands], join= "outer") #outer: takes union

## Checking if they all have a prevalence value (they do)
df_prevalence_combined_filtered = df_prevalence_combined[df_prevalence_combined["prevalence"] != None]

## Saving only the column with words as a Series
df_Dutch_words = df_prevalence_combined_filtered.word
df_Dutch_words = df_Dutch_words.drop_duplicates()

## Apply filtering here
print(df_Gatti[df_Gatti.pseudoword.isin(df_Dutch_words)])
df_Gatti_clean = df_Gatti[~df_Gatti.pseudoword.isin(df_Dutch_words)]

## Saving only the column with pseudowords from pseudowords_Gatti as a Series
df_pseudowords = df_Gatti_clean.pseudoword

    pseudoword     Value
900     pimpen  0.548497

In [57]:

#df_Gatti = df_Gatti.Word[~df_Gatti.isin(df_pseudowords)]
print(len(df_pseudowords))
print(len(df_Gatti_clean))

1499
1499

In [58]:
print(df_pseudowords.head(5))

0    abhert
1    abhict
2    acleat
3    acmure
4     acoed
Name: pseudoword, dtype: object

In [59]:
# encode Dutch words and pseudowords from Gatti et al as uni- and bi-gram vectors
# show the uni-gram and bi-gram encoding of the pseudoword ampgrair
# 2 points for correctly encoding the target strings as uni- and bi-gram vectors

In [60]:
## this is simplified code from the notebook of class one. Permission has been given to use it with the correct reference.

def ngram_featurizer(s, n):

    string_boundary = ["letter"]*(n-1)                        # necessary to encode features such as 'this string begins/ends with this specific symbol'
    s = string_boundary + list(s) + string_boundary

    return [tuple(s[i:i+n]) for i in range(len(s)-n+1)]       # this is where the n-gram featurization actually happens.

In [61]:
## this is code adapted from the notebook of class one. Permission has been given to use it with the correct reference.

# This function encodes all tweets as frequency counts over n-grams
def encode_corpus(corpus, n, mapping=None):

    # creates the appropriate mapping dictionary if it does not exist yet
    if not mapping:
        all_ngrams = set()
        for instance in corpus:
            # get a comprehensive set of all n-grams in the corpus
            all_ngrams = all_ngrams.union(
                set(ngram_featurizer(instance, n))
                )

        # map each n-gram to an integer which will index the feature matrix
        mapping = {ngram: i for i, ngram in enumerate(sorted(all_ngrams))}

    ## creates a dictionary with as key the pseudoword and as value the ngrams present
    dictionary = {}
    for pseudoword in df_pseudowords:
        lst = [0 for i in range(len(mapping))]

        ngrams = ngram_featurizer(pseudoword, n)
        for ngram in ngrams:
            ngram_index = mapping[ngram]
            lst[ngram_index] += 1

        dictionary[pseudoword] = lst    

    return dictionary, mapping

dictionary_unigram, mapping_unigram = encode_corpus(list(df_pseudowords), 1)
dictionary_bigram, mapping_bigram = encode_corpus(list(df_pseudowords), 2)

In [62]:
print(dictionary_unigram["ampgrair"])
print(dictionary_bigram["ampgrair"])

[2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [63]:
##getting words from df_speed

speed_words = df_Speed["Word"]
print(speed_words.head(5))

speed_valence = df_Speed["Valence"]
print(speed_valence.head(5))

0    mama
1      ja
2    papa
3     nee
4    kaka
Name: Word, dtype: object
0    4.000000
1    3.894737
2    3.722222
3    2.350000
4    2.050000
Name: Valence, dtype: float64

In [64]:
##encoding speed_words into unigrams and bigrams

# This function encodes all tweets as frequency counts over n-grams
def encode_corpus(corpus, n, mapping=None):


    if not mapping:
        all_ngrams = set()
        for instance in corpus:
            # get a comprehensive set of all n-grams in the corpus
            all_ngrams = all_ngrams.union(
                set(ngram_featurizer(instance, n))
                )

        # map each n-gram to an integer which will index the feature matrix
        mapping = {ngram: i for i, ngram in enumerate(sorted(all_ngrams))}

    # create a feature matrix of the appropriate dimensionality
    word_list = np.zeros((len(corpus), len(mapping)))
    for i, instance in enumerate(corpus):
        for ngram in ngram_featurizer(instance, n):
            try:
                # access the right column given the n-gram being processed
                word_list[i, mapping[ngram]] += 1
            except KeyError:
                # if the current n-gram is new, skip it
                pass

    return word_list, mapping

speed_unigram, word_mapping_unigram = encode_corpus(list(speed_words), 1, mapping_unigram)
speed_bigram, word_mapping_bigram = encode_corpus(list(speed_words), 2, mapping_bigram)

In [65]:
## encodes pseudowords as unigrams and bigrams
## uses the same mapping as word uni/bi grams
pseudoword_unigrams, pseudoword_mapping_unigram = encode_corpus(list(df_pseudowords), 1, mapping = word_mapping_unigram)
pseudoword_bigrams, pseudoword_mapping_bigram = encode_corpus(list(df_pseudowords), 2, mapping = word_mapping_bigram)

In [66]:
# use word valence estimates from Speed and Brysbaert (2024) to train
# - a uni-gram model
# - a bi-gram model
# 2 points for correctly trained models

In [67]:
## fit a linear model (fits speed_valence to speed_unigrams) 
from sklearn.linear_model import LinearRegression

lm_unigrams = LinearRegression()
lm_unigrams.fit(speed_unigram, speed_valence)

LinearRegression()

In [68]:
## fit a linear model (fits speed_valence to speed_bigrams) 
from sklearn.linear_model import LinearRegression

lm_bigrams = LinearRegression()
lm_bigrams.fit(speed_bigram, speed_valence)

LinearRegression()

In [69]:
# apply trained models to predict the valence of pseudowords from Gatti et al (2024).
# Then apply the same models back onto the training set to see how well they predict the valence of words in Speed and Brysbaert (2024).
# 2 points for correctly applied models

In [70]:
## uses LM_unigrams to predict valence of pseudowords
pw_unigram_valence_pred = lm_unigrams.predict(pseudoword_unigrams)
pw_unigram_valence_pred

array([2.9194398 , 2.93511517, 3.0038439 , ..., 2.84128972, 2.83916586,
       2.79437764], shape=(1499,))

In [71]:

## uses LM_bigrams to predict valence of pseudowords
pw_bigram_valence_pred = lm_bigrams.predict(pseudoword_bigrams)
pw_bigram_valence_pred

array([3.32124685, 3.12371612, 3.23527349, ..., 2.85855727, 2.918002  ,
       3.04808902], shape=(1499,))

In [72]:
# Then apply the same models back onto the training set to see how well they predict the valence of words in Speed and Brysbaert (2024).
## What???? 
##Do they want me to test the model on the same data as the training set?
word_unigram_valence_pred = lm_unigrams.predict(speed_unigram)
print(word_unigram_valence_pred)
word_bigram_valence_pred = lm_bigrams.predict(speed_bigram)
print(word_bigram_valence_pred)

[2.97421461 3.0497127  2.99818918 ... 2.96122497 2.95093093 2.9106144 ]
[3.16593936 3.03482543 3.22484488 ... 2.72045914 2.65380964 3.00794428]

In [73]:
# compute the Spearman correlation coefficients between true valence and predicted valence under both uni- and bi-gram models for
# - words from Speed and Brysbaert (2024)
# - pseudowords from Gatti and colleagues (2024)
# show both correlation coefficients.
# 2 points for the correct Spearman correlation coefficients (rounded to the third decimal place)

In [74]:
## computing spearman's r between predicted word valence and trye word valence
from scipy.stats import spearmanr
print(spearmanr(word_unigram_valence_pred, speed_valence))
print(spearmanr(word_bigram_valence_pred, speed_valence))

SignificanceResult(statistic=np.float64(0.08747282146010639), pvalue=np.float64(5.82250941925177e-42))
SignificanceResult(statistic=np.float64(0.3125232744970933), pvalue=np.float64(0.0))

In [ ]:
## computing spearman's r between predicted pseudword valence and true pseudoword valence
from scipy.stats import spearmanr
true_pseudoword_valence = df_Gatti_clean["Value"] ##This is probably the wrong colum
print(spearmanr(pw_unigram_valence_pred, true_pseudoword_valence))
print(spearmanr(pw_bigram_valence_pred, true_pseudoword_valence))

SignificanceResult(statistic=np.float64(0.26242997642514654), pvalue=np.float64(4.963771681191055e-25))
SignificanceResult(statistic=np.float64(0.13800270585374674), pvalue=np.float64(8.12782680004903e-08))

**Task 2** (*8 points available, see breakdown below*)

Again following Gatti and colleagues, you should encode the target strings (pseudowords and Dutch words from Speed and Brysbaert) as fastText embeddings, train a multiple regression model on Dutch words and apply it to the pseudowords in Gatti et al. You should finally report the Spearman correlation coefficient between observed and predicted valence for both words and pseudowords.

You should use the pre-trained fastText model for Dutch, available at this page: https://fasttext.cc/docs/en/crawl-vectors.html

Finally, you should answer two questions about the fastText model (see below).

In [76]:
# load the fastText model
# 1 point for correctly loading the appropriate fastText model

What is the dimensionality of the pre-trained Dutch fastText embeddings? (*1 point for the correct answer*)

What minimum and maximum n-gram size was specified for training this fastText model? (*1 point for the correct answer*)

In [77]:
# encode Dutch words and pseudowords as fastText embeddings
# show the first 20 values of the embedding of the word 'speelplaats' and of the pseudoword 'danchunk'
# 2 points for correctly encoding words and pseudowords with fastText

In [78]:
# train regression model on word valence
# 1 point for correctly training the regression model

In [79]:
# apply the trained model to predict the valence of pseudowords from Gatti et al (2024).
# Then apply the same model back onto the training set to see how well it predicts the valence of words in Speed and Brysbaert (2024).
# 1 point for correctly applied model

In [80]:
# compute the Spearman correlation coefficients between true valence and predicted valence for
# - words from Speed and Brysbaert (2024)
# - pseudowords from Gatti and colleagues (2024)
# show the correlation coefficient.
# 1 point for the correct Spearman correlation coefficients (rounded to the third decimal place)

**Task 3** (*6 points available, see breakdown below*)

Now you are asked to extend the work by Gatti et al by also considering the representations learned by a transformer-based models, in detail *RobBERT v2* (https://huggingface.co/pdelobelle/robbert-v2-dutch-base). You should follow the same pipeline as for the previous models, encoding both Dutch words from Speed and Brysbaert (2024) and the pseudowords from Gatti et al using the embedding of each string at layer 0, before positional information is factored in. If a string consists of multiple tokens, average the embeddings of all tokens to produce the embedding of the whole string. Then train a multiple regression model on the valence of Dutch words, apply it to the pseudowords, and compute the Spearman correlation between observed and predicted ratings.

Use the HuggingFace model card for RobBERT v2 to check how to access it.

I recommend saving the embeddings to file once you have generated them and you know they are correct: embedding thousands of strings takes some time, and you don't want to have to do it again. For the same reason, develop your code by considering only a small fractions of the words and pseudowords, in order to quickly see if something is wrong. Only when you are positive it works, embed all strings.

In [81]:
# load and instantiate the right model
# 1 point for loading the right model
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("pdelobelle/robbert-v2-dutch-base")
model = AutoModelForMaskedLM.from_pretrained("pdelobelle/robbert-v2-dutch-base")

In [82]:
# encode the words and pseudowords using RobBERT v2. I've used the free GPU runtime on COLAB to speed things up,
# but in this case you need to batch the words and pseudowords. You can use the function below to create batches
# but you will have to pay attention at how you store embeddings.
# show the first 20 values of the embedding of the word 'miauwen' and of the pseudoword 'lixthless'
# 2 points for correctly encoding words and pseudowords

def chunks(lst, n):

    """Chunks a list into equal chunks containing n elements. Returns a list of lists."""

    chunked = []
    for i in range(0, len(lst), n):
        chunked.append(lst[i:i + n])
    return chunked

In [112]:
embedding_layer = model.get_input_embeddings()

In [155]:
import torch
## encode the words and pseudowords using RobBERT v2.
speed_words_encoded = [tokenizer.encode(word) for word in speed_words]
speed_words_embedded = [embedding_layer(torch.tensor(encoding)).mean(dim=0).detach() for encoding in speed_words_encoded]
df_pseudowords_encoded = [tokenizer.encode(word) for word in df_pseudowords]
df_pseudowords_embedded = [embedding_layer(torch.tensor(encoding)).mean(dim=0).detach() for encoding in df_pseudowords_encoded]

df_words_robbert = pd.DataFrame(data={"word":speed_words,"encoded":speed_words_encoded,"embedded":speed_words_embedded})
df_pseudowords_robbert = pd.DataFrame(data={"word":df_pseudowords,"encoded":df_pseudowords_encoded,"embedded":df_pseudowords_embedded})

df_words_robbert.head(5)

   word             encoded                                           embedded
0  mama   [0, 182, 4828, 2]  [tensor(0.0450), tensor(-0.0272), tensor(-0.00...
1    ja        [0, 1732, 2]  [tensor(0.0360), tensor(0.0092), tensor(0.0186...
2  papa  [0, 15638, 115, 2]  [tensor(-0.0531), tensor(-0.0346), tensor(0.05...
3   nee       [0, 10405, 2]  [tensor(0.0728), tensor(-0.0266), tensor(0.068...
4  kaka  [0, 264, 14155, 2]  [tensor(0.0027), tensor(-0.0084), tensor(0.039...

In [158]:
## Complete embeddings of 'miauwen' and 'lixthless'
display("miauwen:")
display([emb for emb in df_words_robbert[df_words_robbert.word=="miauwen"].embedded])

display("lixthless:")
display([emb for emb in df_pseudowords_robbert[df_pseudowords_robbert.word=="lixthless"].embedded])

'miauwen:'

[tensor([ 1.1899e-02, -4.0190e-02, -1.6765e-02, -3.7450e-03,  1.1487e-03,
          3.8893e-02,  5.1970e-02, -3.9541e-02,  3.9526e-02,  1.6261e-02,
          3.9671e-03, -4.0829e-02,  6.4208e-03,  1.3344e-02, -2.4363e-02,
          5.1837e-02,  4.1399e-03, -1.3986e-02,  1.6364e-02,  1.5255e-04,
          5.6306e-02, -3.3568e-02, -1.0271e-02,  1.9151e-02,  4.2883e-02,
          8.5226e-03, -1.8045e-02, -4.6236e-02,  4.5677e-02,  1.8481e-02,
         -1.1335e-02, -6.8286e-03, -1.3582e-02, -1.9128e-02,  7.0255e-02,
         -1.1421e-03, -1.2609e-02, -1.8793e-02,  6.6285e-02, -2.6451e-02,
          2.1974e-02, -5.7495e-03, -3.1453e-02, -3.7613e-02, -1.2099e-02,
         -3.6929e-02, -3.9874e-02,  2.5449e-03,  1.9549e-02, -2.1111e-03,
         -3.9183e-03,  1.5636e-03,  2.7190e-02,  7.2924e-03,  4.7180e-02,
         -1.6073e-02,  3.3189e-02, -4.6309e-03,  1.3357e-02,  1.2779e-02,
          1.7218e-02, -2.8705e-02,  2.4690e-02, -1.5680e-02, -5.1582e-02,
         -6.4883e-03, -2.3327e-02,  8.8151e-03, -8.8737e-03, -4.8011e-02,
          3.0667e-02,  1.4047e-02, -3.3621e-02,  7.4923e-02, -5.7482e-03,
          2.3574e-02, -3.2737e-02,  5.3888e-02,  3.1601e-02,  3.1412e-02,
         -3.1245e-02, -1.2735e-02,  3.2211e-02,  2.9625e-02, -2.0810e-02,
         -6.0767e-03, -4.1917e-02, -7.4430e-02, -1.4828e-02, -1.7774e-02,
         -3.6825e-02, -2.0384e-04,  5.2667e-02, -4.2300e-02, -1.0734e-02,
          1.0171e-02,  5.2400e-02,  1.1883e-02, -2.4734e-02, -2.2679e-02,
          3.5901e-03,  1.9987e-02, -4.9256e-02, -3.4644e-02,  3.1532e-02,
         -5.8959e-02,  4.2057e-02,  9.2711e-03,  9.6059e-02, -4.5122e-02,
          5.5876e-03,  6.0079e-03,  3.8127e-02,  8.8663e-03,  5.1369e-02,
         -4.0691e-02,  5.6127e-02, -1.9887e-02,  9.2038e-03,  3.2316e-02,
         -7.1076e-03, -3.8588e-02,  2.9022e-02,  4.7682e-03,  5.2611e-02,
         -5.3237e-04, -3.9598e-02,  5.2647e-02, -1.4286e-02,  1.0181e-02,
          6.4138e-03,  2.4139e-02,  1.6277e-02, -3.7650e-02, -1.2254e-02,
         -4.7293e-02,  2.5469e-02, -4.5745e-03, -5.9064e-03, -2.6278e-02,
         -1.8565e-02,  5.3099e-02, -7.8728e-03,  1.6818e-02, -4.1982e-02,
          1.5287e-02,  3.7546e-02, -1.3742e-02,  2.5408e-03,  8.9342e-03,
          4.5463e-02,  3.1554e-02, -3.1002e-02,  1.3402e-02,  6.3748e-03,
         -3.4289e-03, -4.3503e-02,  2.6298e-02, -3.5574e-02,  1.5771e-02,
         -1.5451e-02,  3.3443e-02,  3.1607e-02,  7.6962e-02, -4.5612e-02,
         -3.9368e-02, -5.1571e-02,  3.7191e-02,  4.9052e-02, -5.4886e-02,
          2.1924e-02, -1.5968e-02,  8.8381e-03,  1.1695e-02, -7.0524e-03,
         -2.4476e-02, -1.0503e-02, -5.7604e-02, -4.0440e-02, -2.2456e-02,
          1.5630e-02,  1.1428e-02, -4.1756e-02, -2.3532e-03,  4.2136e-02,
         -5.9701e-02, -2.2366e-02, -2.4551e-02,  2.6325e-02,  2.7710e-02,
          1.9730e-03, -1.4646e-02, -4.5956e-02,  7.1928e-03, -2.1726e-02,
         -4.8355e-02, -1.1039e-01, -3.8458e-03,  4.2723e-02, -2.5905e-02,
          2.8050e-02,  2.0777e-02,  1.3100e-02, -2.4434e-02, -5.0112e-03,
         -1.8244e-02, -3.6147e-02, -4.6703e-02, -1.0006e-01,  8.4125e-02,
          4.5006e-02,  2.1410e-02,  6.9807e-02, -2.8086e-02, -3.8878e-02,
          1.0191e-02, -6.1373e-02,  6.3071e-02,  1.5453e-03,  7.4476e-02,
          8.9168e-04, -1.9702e-02, -2.2459e-04, -1.0880e-02, -2.8922e-02,
         -7.0580e-02,  5.9955e-03, -2.6224e-02, -3.2421e-02,  3.1990e-02,
         -5.3361e-03, -4.5284e-03, -1.4322e-02, -2.2054e-02, -7.5742e-03,
         -7.9600e-03,  1.4689e-02, -5.7469e-02, -7.1418e-02,  3.7036e-03,
          2.3203e-02,  3.1904e-02, -2.0402e-02, -3.5130e-02, -2.2687e-02,
          5.0827e-02,  2.3023e-02, -2.7284e-02,  9.6224e-03,  1.2135e-02,
         -1.2872e-02,  9.5752e-03, -3.8750e-02, -4.4321e-02, -1.2366e-02,
         -2.8845e-02,  9.5699e-03, -9.4192e-03, -1.7361e-02,  7.6151e-04,
          7.2721e-03, -1.9257e-02,  1.6627e-02,  1.5437e-03, -1.1739e-02,
         -1.2552e-02,  6.2771e-02, -2.3552e-02, -3.9495e-02, -3.9418e-02,
          1.9301e-02, -1.1646e-02, -5.7549e-02, -3.2501e-02,  9.9102e-03,
         -1.7058e-02, -1.0333e-02, -3.5071e-02, -5.4760e-03,  2.2275e-02,
          4.3124e-02,  8.1255e-02,  6.2989e-03,  1.7795e-02, -2.4598e-02,
          2.9804e-02,  5.9570e-02,  2.7112e-03,  8.3187e-03, -4.8953e-02,
          1.6101e-02, -1.4806e-02, -2.3343e-03,  1.3166e-02, -1.4823e-02,
         -2.1224e-02,  1.2768e-01, -4.4451e-02, -1.8096e-02,  1.0595e-02,
         -1.8984e-02,  3.7319e-02,  4.9782e-02, -2.3439e-02,  2.9577e-03,
         -3.2195e-03,  5.2581e-03,  4.4327e-02, -8.7151e-03, -2.1118e-03,
         -2.5779e-03,  1.2476e-02,  1.5073e-02,  2.9258e-02, -5.8150e-02,
         -3.9004e-02,  4.2290e-03,  6.7599e-03,  1.4872e-02,  8.7389e-03,
         -6.3992e-02, -4.1351e-02, -9.5697e-03,  1.1435e-02, -2.6375e-02,
          7.3134e-03,  6.6449e-03,  8.0310e-03, -1.2197e-02, -1.2085e-03,
          7.8193e-02,  3.4265e-02, -1.6237e-02,  4.5731e-02, -3.4670e-02,
          5.8908e-03,  5.7914e-02, -4.7554e-03,  3.9740e-03, -1.6033e-03,
         -1.0961e-02, -1.4292e-02, -2.5473e-02,  6.3839e-02,  3.5300e-02,
         -9.4590e-03, -6.2427e-03,  9.1807e-03,  2.8526e-02,  2.5495e-02,
         -2.5232e-02,  5.6627e-02,  3.4699e-02,  3.2220e-02,  1.9237e-02,
          4.4069e-02,  1.4578e-02, -2.9647e-02,  7.0215e-02,  2.0157e-02,
          1.1376e-01,  3.8730e-02, -2.4876e-02, -2.2218e-02, -7.4102e-02,
         -1.9578e-02, -1.0333e-02, -1.9784e-02, -4.5431e-02, -5.5884e-02,
         -4.0716e-02, -1.4671e-02,  2.8345e-02,  2.2518e-02,  5.6451e-03,
          1.4466e-02,  2.0370e-02, -5.5470e-02,  5.6719e-02,  1.8242e-02,
          8.4559e-04,  4.7155e-03, -4.6621e-02, -1.3904e-02, -9.5231e-03,
         -4.2746e-02,  5.1903e-02, -3.6146e-03,  1.7462e-03,  1.0085e-02,
         -4.6934e-02, -9.4794e-03, -5.1614e-02, -2.1912e-02,  3.8303e-02,
         -4.3322e-02, -1.5699e-02, -4.9331e-02,  1.3508e-02, -9.2777e-03,
          1.4251e-02,  1.4998e-02, -4.3761e-02,  2.8448e-02,  3.6441e-02,
          1.6418e-02,  3.0877e-02,  2.6917e-02, -1.3722e-02, -1.4507e-02,
          2.7960e-02,  2.2765e-02, -1.8241e-02,  1.8106e-02, -2.2544e-02,
          2.0311e-02, -5.2418e-02,  1.1489e-01, -5.3583e-03,  8.6215e-03,
         -4.2078e-02,  3.4306e-02,  2.9864e-02, -2.0245e-02, -2.2685e-02,
         -1.1389e-03,  1.6212e-02,  2.1170e-02,  3.9330e-02,  2.9303e-02,
          4.3493e-02, -4.1668e-02, -8.0155e-03,  9.8943e-03,  1.9559e-02,
          2.1074e-02, -1.4853e-02,  2.1768e-03,  2.9228e-02, -2.1422e-02,
          2.3309e-02, -2.6131e-02, -1.3374e-02,  5.0228e-03,  4.5116e-02,
          8.4855e-03,  2.1456e-02, -7.0796e-03,  1.1305e-02,  1.1868e-02,
          1.8783e-02,  5.4530e-02,  9.1711e-04,  1.4880e-03,  4.3104e-03,
         -2.6051e-02, -3.1390e-02, -3.2538e-02, -2.0991e-03,  3.1405e-02,
         -1.0343e-02, -3.2199e-02, -4.6635e-02,  5.1738e-02,  8.3125e-03,
          1.4323e-02,  3.6286e-03,  9.2846e-04,  3.4436e-02,  2.8724e-02,
         -4.6052e-03, -1.8458e-02,  8.8795e-03,  2.4006e-02, -3.2326e-02,
          2.5810e-02, -2.4241e-02, -2.1717e-02,  4.4175e-03, -1.1226e-02,
         -1.5207e-02,  2.3029e-02,  4.8105e-02, -3.1125e-03, -1.3040e-02,
         -2.5827e-02,  2.4335e-02, -1.1208e-02,  1.6818e-02,  4.1731e-02,
          1.6160e-03,  4.7358e-02,  3.1387e-02, -1.2653e-03,  1.2401e-02,
          1.5223e-03,  4.0362e-02, -1.3391e-02, -3.1908e-02, -2.0316e-02,
          5.8297e-02, -1.7126e-02, -4.4971e-02,  2.8961e-02,  8.4150e-03,
          3.9100e-02, -2.1790e-02,  6.5214e-02, -5.0718e-02,  3.8852e-02,
         -4.4800e-02,  4.4495e-02,  2.7203e-02, -6.8120e-02, -4.7047e-02,
          1.6809e-02,  5.8135e-02, -5.9945e-03,  1.4182e-02, -2.6403e-02,
         -2.2242e-02, -3.4330e-02,  3.1227e-02, -4.5199e-03,  4.9908e-04,
         -3.7108e-02,  1.0844e-02,  1.2924e-02,  2.6988e-02, -8.5354e-03,
          1.3636e-02,  7.0166e-02, -6.6424e-02,  5.8148e-03,  4.0601e-02,
          3.9235e-03, -1.8891e-06, -3.1110e-02,  1.8634e-02, -3.6091e-03,
         -9.0638e-03,  2.2701e-02, -5.8832e-02,  4.1844e-02, -4.3042e-02,
         -3.4962e-03,  1.9941e-02, -8.6196e-02, -4.1812e-02,  2.6701e-02,
          4.5407e-04,  4.9564e-02, -2.2172e-02, -3.0696e-02, -6.9103e-02,
          2.0047e-04,  4.3538e-02, -5.4775e-02,  5.1876e-02, -8.3359e-03,
         -1.1687e-02, -1.3844e-02,  2.5672e-02,  7.7131e-02,  3.0154e-02,
         -2.9407e-02, -1.2932e-02,  2.7722e-02,  5.9465e-02,  8.3669e-03,
          2.2551e-02,  5.0454e-02,  3.1610e-02, -1.8681e-02, -3.6970e-02,
          1.8609e-02,  4.2202e-02,  2.4199e-02,  1.0913e-02, -1.7744e-02,
         -3.7279e-02, -5.3960e-03,  3.4983e-02,  4.2055e-02, -3.1454e-02,
          3.5070e-02,  8.7069e-03,  1.7573e-02, -3.1964e-02, -9.8548e-03,
          2.0703e-02,  4.4613e-03, -1.1714e-02,  4.1248e-02, -4.0623e-02,
          7.3421e-03,  2.4228e-02,  3.3509e-02,  2.9917e-02, -5.2261e-02,
          6.8191e-02, -2.2080e-02, -8.1019e-03,  1.8813e-02,  3.1524e-03,
         -1.7306e-02,  3.2067e-03, -2.2923e-02,  2.5175e-02,  4.1300e-02,
         -4.5216e-02, -6.4960e-03,  1.3301e-02, -3.2370e-03,  3.9524e-02,
         -1.4325e-02,  2.9707e-02,  3.7653e-02,  2.7201e-02, -3.5254e-02,
         -1.6780e-02, -6.1806e-02, -1.7018e-02, -4.5555e-02, -4.0508e-02,
         -2.7288e-02,  2.6743e-02,  2.6782e-02, -1.0813e-02, -2.3457e-02,
          1.6503e-02,  2.7114e-02,  3.7289e-02, -8.3419e-03,  3.9827e-02,
          3.2842e-02,  2.8050e-03,  2.2579e-02, -7.5642e-03,  2.9363e-02,
          3.5490e-02,  2.4902e-02, -6.2928e-02,  1.9975e-02,  3.5461e-02,
         -2.3273e-02, -3.0702e-02,  5.6163e-02,  2.0383e-02,  1.4019e-02,
          1.4600e-02, -7.2684e-02,  4.2443e-02, -3.6877e-02,  1.6892e-02,
          1.7535e-02,  2.2931e-02, -6.9980e-02,  5.6251e-02,  1.6943e-03,
         -5.3785e-03,  2.0505e-02,  3.8291e-03,  8.4378e-03, -2.5944e-03,
          3.3719e-02,  1.2169e-02,  1.6930e-02, -2.7875e-02,  4.8436e-03,
          2.7523e-02,  7.9603e-03,  1.1417e-02,  1.0450e-02, -5.3289e-03,
          4.9022e-02,  2.4328e-02,  2.3518e-02,  3.5819e-02,  9.3815e-04,
         -4.5950e-03,  1.4430e-02,  1.9458e-02, -3.5786e-02, -2.4019e-03,
          2.1452e-02,  5.2971e-02, -3.1220e-02, -2.2434e-03, -4.0062e-02,
          4.0540e-02, -2.1956e-02, -4.2897e-02,  2.5279e-02, -4.5727e-02,
         -4.5161e-03, -2.5686e-02,  1.7930e-02,  2.4368e-02, -1.0006e-02,
          5.4349e-02, -1.4660e-02,  4.0640e-03, -3.6972e-02,  6.1247e-02,
          2.1861e-02,  2.2934e-02,  4.7729e-03, -4.9179e-03, -3.3714e-02,
          6.8333e-03,  3.2899e-02,  1.2456e-03, -1.0592e-02,  7.3934e-03,
         -5.1326e-02, -6.4367e-02,  4.0091e-02, -6.7572e-03,  2.9523e-02,
         -5.6418e-03, -5.1002e-02, -1.1550e-02, -4.0024e-02,  1.8707e-02,
         -2.1089e-02,  3.0676e-02, -7.0429e-04,  1.0765e-03, -2.3376e-02,
          4.1774e-02, -5.2595e-03,  9.2710e-03,  5.0036e-03, -4.6475e-02,
         -1.9916e-02,  3.5444e-02,  3.5513e-02,  2.5326e-02, -2.1125e-02,
          1.0414e-02, -3.4410e-03,  4.4173e-02,  3.3370e-02,  2.4627e-02,
          1.7604e-02, -1.2239e-02, -5.3015e-02,  4.4815e-02, -2.4369e-02,
          1.5863e-02, -3.7806e-02,  3.0255e-02, -1.9551e-02,  6.2804e-02,
         -5.7467e-03, -4.4086e-03, -6.1834e-02, -2.7167e-02, -6.5595e-02,
         -5.1164e-03,  1.9005e-02, -1.3081e-02,  2.5602e-03,  4.6985e-02,
         -3.6135e-02, -3.2162e-02,  3.0543e-02])]

'lixthless:'

[tensor([-9.3611e-03,  2.8512e-02, -3.5070e-02,  1.2102e-02, -2.6583e-03,
          2.2588e-02,  3.1600e-02, -2.1595e-02, -1.0953e-02,  2.8629e-02,
         -5.6458e-03, -5.4080e-04, -5.6529e-02,  5.6122e-02, -2.7978e-02,
         -1.9987e-03,  3.5793e-02, -2.0458e-02,  2.6065e-02, -1.0271e-02,
          6.4451e-02,  2.5414e-02,  1.5071e-02, -6.0665e-02,  6.9074e-02,
         -1.4615e-02, -8.1531e-03, -9.3363e-03,  6.3506e-02,  1.0140e-02,
         -2.9505e-02, -2.6320e-02, -7.2356e-02, -3.8170e-03,  3.0107e-02,
          7.7828e-03, -4.3065e-03, -1.8814e-03,  2.8715e-02, -1.3859e-02,
         -1.5253e-02,  1.0187e-02, -4.0616e-02,  2.5576e-03, -4.7602e-02,
         -1.0338e-02, -9.3117e-02,  9.6509e-03,  5.7190e-02,  1.7209e-02,
          6.5899e-03,  6.3868e-03,  3.8574e-02, -1.1296e-02,  4.9236e-02,
         -3.1430e-02,  1.2906e-02,  1.5643e-02,  3.7798e-02, -1.0271e-01,
          2.1899e-02,  1.0494e-02,  4.3023e-02,  1.2498e-02, -1.0685e-02,
          6.3675e-03, -1.0282e-02,  1.5557e-02, -6.4412e-02, -5.6852e-02,
          3.6130e-02, -2.9675e-02,  1.1366e-02,  7.6725e-02,  9.9398e-03,
         -2.4975e-02,  8.2091e-03, -2.1383e-02,  6.1624e-02, -2.1063e-02,
          6.8881e-03,  6.5037e-03, -1.8386e-02,  4.6100e-02, -1.7351e-02,
         -3.3082e-02, -1.6267e-02, -3.1351e-02, -1.5363e-02,  1.7128e-03,
          3.5246e-02, -2.0296e-02,  2.2885e-02, -4.3490e-02, -1.5895e-02,
          4.3228e-03, -1.3206e-02,  3.4918e-03,  7.8566e-02, -1.0272e-02,
          5.7712e-03, -1.7135e-02, -7.2876e-03, -2.0648e-02,  1.5207e-02,
          6.6217e-03,  3.9574e-02, -1.2507e-02,  5.5949e-02, -3.6429e-02,
         -4.5432e-02,  4.0557e-02,  8.3257e-02, -2.2382e-02, -3.7232e-02,
         -7.2822e-02,  6.2366e-02,  1.5250e-02, -6.2215e-03,  6.5969e-03,
          2.0651e-02, -7.0018e-02,  2.2487e-02, -6.7470e-02,  3.2834e-02,
         -9.7095e-02, -3.6393e-02,  7.3370e-02, -3.3071e-02, -1.6477e-03,
          9.3206e-03,  2.4597e-02, -2.3873e-02, -3.4041e-02,  4.7442e-02,
          8.3250e-03, -1.7215e-02,  3.8192e-02, -1.0213e-02, -5.0278e-02,
         -2.5026e-02,  6.2305e-03, -1.0458e-02,  1.2625e-02, -3.6029e-02,
         -8.8274e-03, -1.2846e-02, -4.6864e-02,  6.5000e-03, -1.0902e-02,
          5.0112e-02, -2.4793e-02,  2.1237e-02, -3.1178e-02, -2.3940e-02,
          2.3347e-02, -2.8467e-02, -4.2333e-02, -4.7567e-02, -3.8514e-03,
         -3.4744e-02, -3.9777e-02,  6.0639e-03,  2.8200e-02, -2.7492e-02,
         -7.3943e-03, -4.1600e-02, -5.5008e-02, -3.8223e-02,  2.5723e-02,
          1.2019e-02, -2.0961e-02, -3.4945e-02, -2.8363e-02, -3.6426e-02,
         -1.6717e-02, -2.3274e-02,  1.7982e-02, -4.6512e-02, -7.4426e-03,
         -2.1095e-02,  2.3969e-02,  2.2755e-03, -4.3206e-02,  5.3406e-02,
         -6.0979e-02, -4.0105e-02, -4.6308e-03, -1.0137e-02,  4.3525e-02,
         -1.1338e-02,  2.3988e-02,  1.8706e-02, -1.4562e-02,  2.6967e-03,
         -2.0337e-02, -4.8113e-02,  3.6131e-03, -6.2483e-02, -2.1958e-02,
          4.6076e-02, -1.3337e-02, -1.7641e-02, -8.2054e-03, -5.4932e-02,
          2.1900e-02, -3.0314e-02, -8.6091e-02, -8.1283e-02,  1.6899e-02,
         -1.0372e-02, -5.5400e-04,  2.1226e-02, -1.0161e-02, -2.8707e-02,
          1.3578e-02,  2.0856e-02, -2.3609e-03,  3.6378e-03,  5.3446e-02,
          8.7176e-02,  5.5366e-03, -8.3027e-03, -3.1757e-02,  3.2903e-02,
         -2.9820e-02,  2.4064e-02, -5.0641e-04,  3.5292e-02, -6.3400e-03,
         -1.8098e-02,  1.9439e-02, -3.6453e-02, -3.8015e-02, -2.4813e-02,
          2.1103e-02,  3.8132e-02, -1.8937e-02, -1.3035e-02,  2.1404e-02,
          6.8111e-03,  3.7702e-02,  1.0003e-02, -3.1411e-02, -2.0086e-02,
          5.3188e-02,  8.6464e-03, -3.0312e-02,  2.0004e-02, -1.7312e-02,
         -3.6404e-03, -3.5717e-02, -7.3157e-02, -2.1279e-02, -9.4601e-03,
         -8.3708e-02,  8.3695e-03, -1.4589e-02, -3.0324e-02, -1.6953e-02,
         -1.6312e-02,  2.0457e-02,  1.6623e-02,  3.3564e-02,  3.9724e-02,
          2.2475e-03,  5.3145e-02, -1.0164e-01, -9.1080e-03,  2.1896e-02,
          3.6370e-02, -3.3484e-02, -3.4027e-02, -1.3449e-02, -2.7452e-03,
         -2.5855e-02,  5.5468e-02, -3.6172e-02, -2.8366e-02,  1.0460e-02,
          3.6409e-02,  3.8224e-02,  1.8043e-04, -4.1028e-02,  5.4393e-03,
          3.7549e-02,  1.4182e-02,  3.5901e-02, -5.9705e-02, -2.6828e-03,
          4.4305e-02,  1.7557e-02,  3.2955e-02, -5.3270e-03,  5.1882e-02,
         -4.0161e-02,  1.2020e-01, -5.0579e-02,  1.9616e-02, -1.5888e-02,
         -2.4107e-02,  5.7581e-02, -2.6999e-02, -3.2186e-03,  3.5375e-02,
          3.1860e-02,  3.5887e-02,  4.9233e-03, -1.3872e-02, -4.6726e-02,
         -7.4134e-04, -8.0740e-02,  1.5683e-03,  2.4111e-02, -7.9384e-02,
         -3.6444e-02, -3.8020e-03, -1.4520e-02, -1.7469e-02, -3.5901e-02,
         -4.0654e-03,  1.7494e-02, -4.5367e-03, -2.1125e-02, -1.9080e-02,
         -2.0205e-02, -1.0496e-02, -4.9757e-02,  7.9058e-03,  4.8931e-03,
          2.2365e-04,  5.6998e-03,  2.1653e-02, -4.2104e-03, -1.1252e-02,
          4.9594e-03,  2.1804e-02, -3.1100e-02, -3.7359e-02, -2.4576e-02,
          2.4141e-02, -1.2884e-02, -6.7723e-03,  2.1369e-02, -1.8695e-02,
         -1.0754e-02, -5.4400e-03,  9.8094e-03,  2.9465e-02,  4.5159e-02,
         -3.5187e-02, -6.8013e-03,  5.2944e-02, -1.6294e-03,  1.9114e-02,
          2.0482e-02,  6.4536e-02,  2.4675e-02,  1.4841e-02, -3.0195e-02,
          8.9023e-02,  1.5627e-02, -2.4416e-02, -1.2035e-03, -7.1631e-02,
         -3.9848e-02,  2.2149e-02, -2.2114e-04, -2.7055e-02, -4.3002e-02,
         -6.3940e-02, -1.2404e-03, -7.0635e-03,  3.8185e-02, -7.8937e-03,
         -2.0414e-03, -4.0683e-03, -5.2201e-02,  4.4174e-02,  3.0584e-02,
         -4.2065e-02,  9.3618e-03, -2.7669e-03, -2.7807e-02, -3.0215e-03,
          2.2194e-02, -1.6146e-02,  2.5464e-02,  2.0616e-02,  2.3443e-03,
          1.9583e-02, -2.0369e-02, -1.5333e-03,  1.5902e-02, -9.2632e-02,
          8.8128e-03, -1.8738e-02, -2.9928e-02, -1.2916e-03,  2.9603e-02,
         -4.2047e-03,  1.9747e-03, -4.6792e-02, -4.5859e-02,  3.3878e-02,
         -1.3477e-02,  3.2551e-02,  1.2585e-02, -1.3493e-02,  3.5989e-02,
          7.3214e-02,  6.2328e-03, -1.0013e-02, -2.0983e-02,  1.5346e-02,
          5.8656e-02, -6.7779e-02,  1.0114e-01, -5.4799e-02, -5.1217e-02,
         -2.7430e-02, -4.0467e-04,  5.4373e-03, -3.7159e-02, -4.9654e-02,
         -4.5017e-03, -1.2096e-02,  3.6947e-02,  5.4873e-02,  8.6522e-03,
          2.0728e-03,  3.4899e-02,  2.7595e-02,  1.3416e-02,  8.5007e-03,
         -2.6795e-02, -4.0304e-02, -2.6860e-02, -1.0520e-01,  4.4842e-02,
          2.5897e-02,  2.4531e-02, -1.0076e-02,  5.3433e-02,  4.2422e-02,
         -1.9992e-04, -3.1788e-02, -1.0273e-02,  2.7707e-02, -7.1283e-03,
          6.0589e-03,  1.3416e-02,  1.0958e-02, -4.4953e-03, -2.1709e-02,
         -1.4798e-02,  5.7763e-03, -1.4008e-02, -1.6170e-02, -1.7036e-02,
         -1.8880e-02, -4.8279e-02, -4.2700e-03,  9.8279e-02,  1.9048e-02,
         -1.3909e-02,  2.2658e-02, -1.7472e-02,  3.8320e-02,  4.1030e-02,
          1.1732e-02, -5.7767e-02, -1.2226e-02,  3.1707e-02, -6.0633e-03,
         -7.5352e-03, -3.7808e-02, -1.7176e-02,  1.3104e-02, -2.4441e-02,
          5.2369e-03, -3.0208e-02,  6.2062e-02,  2.9018e-02,  3.8562e-02,
         -9.2545e-03, -1.3472e-02,  1.9195e-02, -4.9973e-02,  5.0051e-04,
          5.5164e-04, -2.0356e-02, -1.5190e-02,  1.6261e-02,  3.1769e-02,
          3.5055e-02,  8.7403e-03, -8.0470e-04, -5.3508e-02, -5.9728e-02,
         -3.2594e-03, -4.0420e-02, -4.0621e-02, -3.7925e-02, -1.5713e-02,
         -1.9213e-02,  1.1355e-02,  9.1324e-02, -1.5541e-02, -1.7602e-02,
         -3.9675e-02, -2.5191e-02,  2.5439e-02, -3.9641e-02,  3.3376e-02,
         -2.3938e-02,  4.4036e-02,  3.3463e-02, -2.1646e-02,  9.5082e-03,
         -2.4156e-02,  5.2902e-03,  1.4173e-02, -3.4384e-03,  1.1519e-03,
          3.6052e-02,  3.0612e-02, -5.8171e-03, -2.7086e-02,  3.9434e-02,
          2.2165e-06,  4.5586e-02, -1.1193e-03, -7.4671e-03, -1.2448e-03,
         -3.5141e-02,  4.8973e-04, -2.2870e-02,  2.0846e-02, -1.8347e-02,
          2.2929e-02, -2.1850e-02, -6.7147e-04,  1.6667e-02, -4.1927e-02,
         -3.5782e-03,  3.5160e-02, -5.5730e-02, -3.5700e-02,  7.0963e-04,
          2.0105e-02,  7.3807e-02, -2.2271e-02,  5.2027e-03,  1.0130e-02,
         -2.5270e-02,  3.6368e-02,  2.3833e-02,  5.2375e-02, -2.5619e-02,
         -2.1079e-02, -4.6776e-02,  6.3106e-02,  2.5669e-02,  1.8150e-02,
         -1.1781e-02, -2.1109e-02, -2.2552e-02, -2.3105e-02,  5.4389e-02,
         -1.4387e-02,  2.8700e-02,  2.3544e-02,  1.5808e-02,  1.1716e-02,
         -1.5123e-02,  5.9119e-03,  3.7586e-02,  2.5621e-02,  7.0198e-04,
         -2.9749e-03, -1.3750e-02,  2.1814e-02,  3.2847e-04,  2.3244e-02,
          1.2400e-02, -2.2970e-02,  2.4580e-02, -2.9574e-02,  7.0127e-03,
          2.5063e-02,  3.1389e-02,  3.9050e-03,  3.5736e-02,  1.5034e-02,
          2.7743e-02, -1.3452e-02,  1.3453e-02, -3.7805e-03, -2.9656e-03,
          6.0024e-02, -1.8364e-02,  1.0902e-02,  8.8153e-03, -4.7193e-03,
         -3.7211e-02,  2.0052e-02, -4.1587e-02,  4.1944e-02,  3.0978e-02,
         -9.5639e-03,  6.6417e-03,  9.7865e-03,  5.4711e-03,  4.5053e-02,
          7.5012e-03,  1.4442e-02,  4.5447e-02,  3.3410e-02, -4.8861e-02,
         -5.0197e-02, -4.7253e-02, -4.5010e-02,  1.1424e-02,  8.4078e-03,
          1.3274e-02, -1.7067e-02, -3.4686e-02, -3.3248e-02,  3.9959e-02,
          3.1206e-03, -5.8988e-03, -3.4170e-03, -6.3881e-03,  3.5939e-02,
          2.3134e-02,  4.0248e-03, -3.5744e-02, -3.0401e-02, -5.4089e-02,
          2.7810e-02,  4.1820e-02, -2.1954e-02, -2.8293e-02,  1.9755e-02,
         -2.4379e-02, -1.1983e-02,  3.7828e-02,  4.8015e-02,  3.6642e-02,
         -2.7297e-02, -5.7543e-02,  3.2364e-02, -5.5917e-02, -2.2205e-02,
          9.1396e-03, -4.9490e-03, -4.1853e-02,  3.1510e-02, -5.7761e-03,
          2.3304e-02, -1.2423e-02,  3.9423e-03,  4.1213e-02, -6.9169e-02,
          4.8663e-03, -3.4461e-02, -1.9471e-02, -1.8842e-02, -5.0605e-03,
         -9.4064e-03,  4.1275e-02,  4.4870e-03, -2.7212e-02, -4.6445e-02,
          6.0895e-02, -6.8850e-03, -2.1487e-02,  7.2347e-02,  1.9357e-02,
         -4.5504e-02, -1.7244e-02,  7.4675e-03, -4.8733e-02,  4.0431e-02,
          9.2357e-03,  7.8869e-03, -1.3478e-03, -5.8864e-02, -7.0286e-02,
          2.6242e-03,  8.6656e-03, -3.2452e-03,  1.1851e-02, -5.6401e-02,
         -3.6039e-03, -7.9555e-02, -5.4702e-02,  1.1886e-02, -3.1351e-02,
         -1.4619e-02, -2.5393e-02, -1.8705e-02,  4.3460e-02,  4.9617e-03,
          3.3701e-03, -2.2618e-03, -3.2000e-02,  1.4527e-02, -7.0376e-02,
          1.8842e-02,  3.4284e-02, -6.8561e-05, -2.3478e-02,  1.3312e-02,
         -1.2698e-01, -1.5204e-02, -1.4951e-02, -3.5073e-02,  4.5562e-03,
         -7.4162e-03,  3.5924e-03,  2.9332e-02, -2.1420e-02, -3.0493e-02,
          1.2267e-02, -3.2805e-02, -1.4747e-03, -5.6943e-03,  7.2697e-04,
          6.2178e-02, -1.5538e-03,  1.7353e-02,  1.7081e-02, -3.2450e-02,
         -3.3101e-02,  4.1898e-02,  1.7752e-03, -8.2079e-03, -2.0719e-02,
         -3.2890e-02,  2.3226e-02,  2.7331e-02, -4.2917e-02, -1.2619e-02,
         -8.0044e-03,  1.4549e-02, -5.3885e-02,  5.3948e-02, -4.1369e-02,
         -6.4281e-03, -2.5476e-02,  1.4732e-02, -3.5328e-02,  6.5789e-02,
         -1.8028e-02,  1.3347e-03, -2.0366e-02,  5.6403e-03, -6.1566e-02,
         -3.6351e-02,  3.5402e-03, -2.5019e-02,  1.0313e-02,  6.0534e-03,
         -4.1045e-02, -6.4530e-02,  3.8790e-02])]

In [160]:
## Showing the first 20 values of the embedding of the word 'miauwen' and of the pseudoword 'lixthless'
print("miauwen:", end=" ")
print([emb for emb in df_words_robbert[df_words_robbert.word=="miauwen"].embedded][0][:20])

print("lixthless:", end=" ")
print([emb for emb in df_pseudowords_robbert[df_pseudowords_robbert.word=="lixthless"].embedded][0][:20])

miauwen: tensor([ 0.0119, -0.0402, -0.0168, -0.0037,  0.0011,  0.0389,  0.0520, -0.0395,
         0.0395,  0.0163,  0.0040, -0.0408,  0.0064,  0.0133, -0.0244,  0.0518,
         0.0041, -0.0140,  0.0164,  0.0002])
lixthless: tensor([-0.0094,  0.0285, -0.0351,  0.0121, -0.0027,  0.0226,  0.0316, -0.0216,
        -0.0110,  0.0286, -0.0056, -0.0005, -0.0565,  0.0561, -0.0280, -0.0020,
         0.0358, -0.0205,  0.0261, -0.0103])

In [162]:
df_words_robbert.embedded

0        [tensor(0.0450), tensor(-0.0272), tensor(-0.00...
1        [tensor(0.0360), tensor(0.0092), tensor(0.0186...
2        [tensor(-0.0531), tensor(-0.0346), tensor(0.05...
3        [tensor(0.0728), tensor(-0.0266), tensor(0.068...
4        [tensor(0.0027), tensor(-0.0084), tensor(0.039...
                               ...
23981    [tensor(0.0260), tensor(-0.0018), tensor(-0.02...
23982    [tensor(-0.0575), tensor(0.0041), tensor(0.003...
23983    [tensor(0.0229), tensor(-0.0503), tensor(0.013...
23984    [tensor(-0.0368), tensor(0.0018), tensor(0.004...
23985    [tensor(-0.0287), tensor(-0.0427), tensor(0.01...
Name: embedded, Length: 23986, dtype: object

In [170]:
# train regression model on word valence estimates from Speed and Brysbaert (2024)
# 1 point for correctly training the regression model
lm_embeddings = LinearRegression()
lm_embeddings.fit([elem.numpy() for elem in df_words_robbert.embedded],speed_valence)

LinearRegression()

In [176]:
# apply the trained model to predict the valence of pseudowords from Gatti et al (2024).
# Then apply the same model back onto the training set to see how well it predicts the valence of words in Speed and Brysbaert (2024).
# 1 point for correctly applied model

lm_gatti_embed_valence_pred = lm_embeddings.predict([elem.numpy() for elem in df_pseudowords_robbert.embedded])
print(lm_gatti_embed_valence_pred)
lm_speed_embed_valence_pred = lm_embeddings.predict([elem.numpy() for elem in df_words_robbert.embedded])
print(lm_speed_embed_valence_pred)

[2.9193215 2.7187014 2.5730562 ... 3.0327637 2.826509  2.583156 ]
[3.2153578 3.1907582 3.0835767 ... 2.7967858 2.9106436 3.016904 ]

In [87]:
# compute the Spearman correlation coefficients between true valence and predicted valence for
# - words from Speed and Brysbaert (2024)
# - pseudowords from Gatti and colleagues (2024)
# show the correlation coefficient
# 1 point for the correct Spearman correlation coefficients (rounded to the third decimal place)

In [177]:
print(spearmanr(lm_speed_embed_valence_pred, speed_valence))
print(spearmanr(lm_gatti_embed_valence_pred, true_pseudoword_valence))

SignificanceResult(statistic=np.float64(0.5188060091566226), pvalue=np.float64(0.0))
SignificanceResult(statistic=np.float64(0.1809523963906512), pvalue=np.float64(1.6840632151398347e-12))

**Task 4** (*16 points available, 4 for each question*)

Answer the following questions.

**4a.** Describe the performance of each featurization, comparing
- the performance of a same model between the training and test set
- the performance of different models on the training set
- the performance of different models on the test set

(*4 points available, max 150 words*)

*type your answer here*

**4b.** Compare the correlations you found when training uni-gram, bi-gram, and fastText models on Dutch words and the correlations of similar models trained on English data as reported by Gatti and colleagues; summarize the most important similarities and differences.

(*4 points available, max 150 words*)

*type your answer here*

**4c.** Do you think the performance of the fastText featurization would change if you were to use different n-grams? Would you make them smaller or larger? Justify your answer.

(*4 points available, max 150 words*)

*type your answer here*

**4d.** Do you think that training the same models on uni-grams, bi-grams, fastText and transformer-based embeddings but using valence ratings for Finnish (a language which uses the same alphabet as English but is not a IndoEuropean language) words would yield a similar pattern of results? Justify your answer.

(*4 points available, max 150 words*)

*type your answer here*

**Task 5** (*3 points available*)

Compute the average Levenshtein Distance (aLD) between each pseudoword and the 20 words at the smallest edit distance from it. Consider the set of words you used to filter out pseudowords that happen to be valid Dutch words (the file is available in this OSF repository: https://osf.io/9zymw/) to retrieve the 20 words at the smallest edit distance.

In [88]:
# compute the average Levenshtein distance from each pseudoword to the words used to filter out pseudowords.
# Show the aLD estimate for the pseudowords 'nedukes', 'pewbin', and 'vibcines'
# 3 points for correctly computing aLD for pseudowords

In [89]:
## This code is taken from the first notebook discussed in class. Permission to used materials discussed in class has been given
## as long as proper reference is given.

## This code calculates the edit distance
def edit_distance(source, target, costs={'del': 1, 'ins': 1, 'sub':1}):

    r, c = len(source)+1, len(target)+1
    d = np.zeros((r, c), dtype=int)

    for i in range(1, r):
        for j in range(1, c):
            d[i][0] = i
            d[0][j] = j

    for col in range(1, c):
        for row in range(1, r):
            cost = 0 if source[row-1] == target[col-1] else costs['sub']
            d[row][col] = min(d[row-1][col] + costs['del'],
                              d[row][col-1] + costs['ins'],
                              d[row-1][col-1] + cost)

    return int(d[-1][-1])

In [90]:
## this code calculates the average edit distance of the 20 most similar words for 1 pseudoword
def average_edit_distance(pseudoword, dutch_words):
    edit_distance_list = []
    for word in dutch_words:
        edit_distance_value = edit_distance(pseudoword, word)
        edit_distance_list.append(edit_distance_value)

        if len(edit_distance_list) > 20:
            edit_distance_list.remove(max(edit_distance_list))

    return sum(edit_distance_list)/20


## input a file, returns how many lines there are in the file, so we know which pseudoword to continue with
def retrieve_index(filename):
    open_file = open(filename, "r")
    amount_of_lines = sum(1 for line in open_file)
    open_file.close()
    return amount_of_lines


## input a filename, pseudowords and edit distances will be stored (comma separated) on a new line
def store_in_file(filename):
    amount_of_lines = retrieve_index(filename)
    batch_size = 5 #amount of elements generated before the file gets closed and re-opened (to save results)
    count = 0

    if amount_of_lines == len(df_pseudowords):
        return "all elements are already written to the file"

    open_file = open(filename, "a") 
    for pseudoword in df_pseudowords[amount_of_lines:]:

        # closing and re-opening the file to save
        if count >= batch_size:
            open_file.close()
            open_file = open(filename, "a") 
            count = 0
        count += 1

        string = pseudoword + "," + str(average_edit_distance(pseudoword, df_Dutch_words)) + "\n"                                    
        open_file.write(string)

    open_file.close()

    return "all elements have been written to the file"

store_in_file("edit_distance.txt")

'all elements are already written to the file'

In [91]:
## retrieve the values for 'nedukes', 'pewbin', and 'vibcines'
open_file = open("edit_distance.txt", "r")

for i in range(retrieve_index("edit_distance.txt")):
    line = open_file.readline()
    
    if "nedukes" in line or "pewbin" in line or "vibcines" in line:
        pseudoword, edit_distance_value = line.split(",")
        print (f"pseudoword: {pseudoword}, average edit distance: {edit_distance_value}")

pseudoword: nedukes, average edit distance: 2.9

pseudoword: pewbin, average edit distance: 2.95

pseudoword: vibcines, average edit distance: 3.55

**Task 6** (*3 points available*)

For each pseudoword, record the number of tokens in which RobBERT v2 encodes it.

In [92]:
# record the number of tokens in which RobBERT divides each pseudoword
# show the number of tokens for the pseudowords 'yuxwas', 'skibfy', and 'errords'
# 3 points for correctly mapping pseudowords to number of tokens

**Task 7** (*5 points available, see breakdown below*)

Compute the residuals of the predicted valence under the four regressors trained and applied in tasks 2 to 4. Then, correlate the residuals from all four models with aLD. Finally, correlate the residuals from the RobBERT v2 model with the number of tokens in which each pseudoword is split. Use the Pearson's correlation coefficient.

In [93]:
# compute the residuals from all four regression models fitted before
# 1 point available for correctly computing residuals

In [94]:
# compute the Pearson's correlation between residuals and average LD for all models,
# as well as the correlation between RobBERT v2 residuals and the number of tokens in which each pseudoword
#    is encoded by the RobBERT v2 model.
# show all correlation coefficients
# 4 points for the correct correlation coefficients

**Task 8** What is the relation between the errors each model made and aLD? what about the number of tokens (limited to the RobBERT v2 model)?

(*4 points available, max 150 words*)

*testo in corsivo*